export const productData = [
  {
    name: "Rustic Soft Cheese",
    image: "http://placeimg.com/640/480/food",
    price: "733.00",
    slug: "veniam-repudiandae-non",
    category: "Clothing",
    id: "1",
  },
  {
    name: "Practical Plastic Pizza",
    image: "http://placeimg.com/640/480/nature",
    price: "793.00",
    slug: "dolorem-provident-minima",
    category: "Games",
    id: "2",
  },
  {
    name: "Unbranded Soft Bike",
    image: "http://placeimg.com/640/480/cats",
    price: "757.00",
    slug: "eos-laboriosam-possimus",
    category: "Jewelery",
    id: "3",
  },
  {
    name: "Refined Fresh Towels",
    image: "http://placeimg.com/640/480/people",
    price: "994.00",
    slug: "deserunt-unde-debitis",
    category: "Shoes",
    id: "4",
  },
  {
    name: "Practical Wooden Bacon",
    image: "http://placeimg.com/640/480/animals",
    price: "283.00",
    slug: "modi-consectetur-cupiditate",
    category: "Home",
    id: "5",
  },
  {
    name: "Handcrafted Wooden Computer",
    image: "http://placeimg.com/640/480/abstract",
    price: "850.00",
    slug: "quo-delectus-sit",
    category: "Grocery",
    id: "6",
  },
  {
    name: "Incredible Steel Mouse",
    image: "http://placeimg.com/640/480/cats",
    price: "641.00",
    slug: "illum-rerum-placeat",
    category: "Jewelery",
    id: "7",
  },
  {
    name: "Incredible Metal Bike",
    image: "http://placeimg.com/640/480/nature",
    price: "280.00",
    slug: "molestias-id-minima",
    category: "Automotive",
    id: "8",
  },
  {
    name: "Small Plastic Chair",
    image: "http://placeimg.com/640/480/fashion",
    price: "559.00",
    slug: "qui-aperiam-qui",
    category: "Outdoors",
    id: "9",
  },
  {
    name: "Incredible Cotton Soap",
    image: "http://placeimg.com/640/480/food",
    price: "719.00",
    slug: "earum-fuga-et",
    category: "Garden",
    id: "10",
  },
  {
    name: "Fantastic Rubber Pizza",
    image: "http://placeimg.com/640/480/people",
    price: "170.00",
    slug: "aut-nihil-aut",
    category: "Movies",
    id: "11",
  },
  {
    name: "Handmade Soft Pizza",
    image: "http://placeimg.com/640/480/cats",
    price: "984.00",
    slug: "quaerat-sint-fugit",
    category: "Computers",
    id: "12",
  },
  {
    name: "Awesome Cotton Pizza",
    image: "http://placeimg.com/640/480/food",
    price: "218.00",
    slug: "ipsa-repellendus-quisquam",
    category: "Kids",
    id: "13",
  },
  {
    name: "Ergonomic Metal Hat",
    image: "http://placeimg.com/640/480/city",
    price: "405.00",
    slug: "et-numquam-neque",
    category: "Industrial",
    id: "14",
  },
  {
    name: "Ergonomic Steel Sausages",
    image: "http://placeimg.com/640/480/cats",
    price: "690.00",
    slug: "nam-voluptate-qui",
    category: "Automotive",
    id: "15",
  },
  {
    name: "Unbranded Plastic Computer",
    image: "http://placeimg.com/640/480/nature",
    price: "193.00",
    slug: "maiores-dolor-ut",
    category: "Computers",
    id: "16",
  },
  {
    name: "Refined Concrete Ball",
    image: "http://placeimg.com/640/480/sports",
    price: "896.00",
    slug: "dolorem-aut-et",
    category: "Computers",
    id: "17",
  },
  {
    name: "Intelligent Frozen Gloves",
    image: "http://placeimg.com/640/480/cats",
    price: "434.00",
    slug: "aliquid-odio-quam",
    category: "Sports",
    id: "18",
  },
  {
    name: "Handmade Soft Hat",
    image: "http://placeimg.com/640/480/food",
    price: "173.00",
    slug: "nulla-maiores-molestiae",
    category: "Industrial",
    id: "19",
  },
  {
    name: "Gorgeous Granite Bacon",
    image: "http://placeimg.com/640/480/technics",
    price: "850.00",
    slug: "enim-quibusdam-animi",
    category: "Garden",
    id: "20",
  },
  {
    name: "Gorgeous Concrete Gloves",
    image: "http://placeimg.com/640/480/technics",
    price: "563.00",
    slug: "magni-qui-quaerat",
    category: "Jewelery",
    id: "21",
  },
  {
    name: "Sleek Frozen Soap",
    image: "http://placeimg.com/640/480/sports",
    price: "972.00",
    slug: "autem-cupiditate-sed",
    category: "Tools",
    id: "22",
  },
  {
    name: "Handcrafted Fresh Chair",
    image: "http://placeimg.com/640/480/city",
    price: "485.00",
    slug: "enim-dolorum-laborum",
    category: "Industrial",
    id: "23",
  },
  {
    name: "Handmade Steel Mouse",
    image: "http://placeimg.com/640/480/fashion",
    price: "48.00",
    slug: "similique-aut-officia",
    category: "Shoes",
    id: "24",
  },
  {
    name: "Ergonomic Cotton Keyboard",
    image: "http://placeimg.com/640/480/business",
    price: "398.00",
    slug: "optio-voluptatem-voluptatem",
    category: "Toys",
    id: "25",
  },
  {
    name: "Handcrafted Wooden Salad",
    image: "http://placeimg.com/640/480/nightlife",
    price: "290.00",
    slug: "eaque-reiciendis-aut",
    category: "Jewelery",
    id: "26",
  },
  {
    name: "Rustic Concrete Sausages",
    image: "http://placeimg.com/640/480/people",
    price: "566.00",
    slug: "veniam-rem-vitae",
    category: "Industrial",
    id: "27",
  },
  {
    name: "Handcrafted Metal Car",
    image: "http://placeimg.com/640/480/nightlife",
    price: "729.00",
    slug: "autem-ex-perspiciatis",
    category: "Garden",
    id: "28",
  },
  {
    name: "Rustic Granite Computer",
    image: "http://placeimg.com/640/480/cats",
    price: "22.00",
    slug: "numquam-cum-quaerat",
    category: "Jewelery",
    id: "29",
  },
  {
    name: "Ergonomic Granite Gloves",
    image: "http://placeimg.com/640/480/abstract",
    price: "458.00",
    slug: "quam-voluptatem-voluptate",
    category: "Movies",
    id: "30",
  },
  {
    name: "Practical Cotton Bike",
    image: "http://placeimg.com/640/480/business",
    price: "18.00",
    slug: "ratione-quae-est",
    category: "Computers",
    id: "31",
  },
  {
    name: "Intelligent Wooden Shoes",
    image: "http://placeimg.com/640/480/sports",
    price: "672.00",
    slug: "illo-at-illo",
    category: "Grocery",
    id: "32",
  },
  {
    name: "Licensed Rubber Gloves",
    image: "http://placeimg.com/640/480/animals",
    price: "598.00",
    slug: "quo-laboriosam-aspernatur",
    category: "Tools",
    id: "33",
  },
  {
    name: "Intelligent Soft Computer",
    image: "http://placeimg.com/640/480/city",
    price: "263.00",
    slug: "nihil-aut-consectetur",
    category: "Books",
    id: "34",
  },
  {
    name: "Licensed Cotton Bike",
    image: "http://placeimg.com/640/480/nature",
    price: "906.00",
    slug: "aut-laboriosam-deleniti",
    category: "Automotive",
    id: "35",
  },
  {
    name: "Rustic Plastic Mouse",
    image: "http://placeimg.com/640/480/city",
    price: "957.00",
    slug: "quia-voluptas-quia",
    category: "Electronics",
    id: "36",
  },
  {
    name: "Refined Concrete Fish",
    image: "http://placeimg.com/640/480/nature",
    price: "84.00",
    slug: "laborum-ullam-facilis",
    category: "Computers",
    id: "37",
  },
  {
    name: "Refined Wooden Chicken",
    image: "http://placeimg.com/640/480/abstract",
    price: "536.00",
    slug: "vel-non-autem",
    category: "Toys",
    id: "38",
  },
  {
    name: "Handmade Wooden Shirt",
    image: "http://placeimg.com/640/480/abstract",
    price: "599.00",
    slug: "molestias-ut-aut",
    category: "Games",
    id: "39",
  },
  {
    name: "Handcrafted Frozen Sausages",
    image: "http://placeimg.com/640/480/nature",
    price: "511.00",
    slug: "et-modi-aut",
    category: "Toys",
    id: "40",
  },
  {
    name: "Generic Concrete Shoes",
    image: "http://placeimg.com/640/480/fashion",
    price: "294.00",
    slug: "est-soluta-laborum",
    category: "Movies",
    id: "41",
  },
  {
    name: "Fantastic Soft Table",
    image: "http://placeimg.com/640/480/fashion",
    price: "344.00",
    slug: "perspiciatis-quis-ut",
    category: "Health",
    id: "42",
  },
  {
    name: "Unbranded Steel Mouse",
    image: "http://placeimg.com/640/480/abstract",
    price: "881.00",
    slug: "eligendi-accusantium-consequatur",
    category: "Grocery",
    id: "43",
  },
  {
    name: "Generic Granite Cheese",
    image: "http://placeimg.com/640/480/technics",
    price: "5.00",
    slug: "libero-quas-sint",
    category: "Tools",
    id: "44",
  },
  {
    name: "Handmade Frozen Car",
    image: "http://placeimg.com/640/480/technics",
    price: "966.00",
    slug: "est-dolorem-natus",
    category: "Kids",
    id: "45",
  },
  {
    name: "Licensed Wooden Gloves",
    image: "http://placeimg.com/640/480/animals",
    price: "41.00",
    slug: "doloremque-quisquam-deserunt",
    category: "Clothing",
    id: "46",
  },
  {
    name: "Unbranded Soft Car",
    image: "http://placeimg.com/640/480/fashion",
    price: "901.00",
    slug: "quasi-temporibus-accusantium",
    category: "Computers",
    id: "47",
  },
  {
    name: "Ergonomic Soft Table",
    image: "http://placeimg.com/640/480/cats",
    price: "174.00",
    slug: "qui-molestiae-et",
    category: "Toys",
    id: "48",
  },
  {
    name: "Rustic Plastic Sausages",
    image: "http://placeimg.com/640/480/cats",
    price: "20.00",
    slug: "blanditiis-voluptate-eius",
    category: "Industrial",
    id: "49",
  },
  {
    name: "Tasty Frozen Towels",
    image: "http://placeimg.com/640/480/animals",
    price: "78.00",
    slug: "molestiae-dolores-magnam",
    category: "Computers",
    id: "50",
  },
];
